#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1
start_service() {
    config_load smit
    local enabled bind port adapter
    config_get_bool enabled server enabled 1
    [ "$enabled" = 1 ] || return 0
    config_get bind server bind 127.0.0.1
    config_get port server port 38212
    config_get adapter server adapter /dev/dvb/adapter0
    procd_open_instance
    procd_set_param command /usr/bin/smit --bind "$bind" --port "$port" --adapter "$adapter"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
service_triggers() {
    procd_add_reload_trigger smit
}
